// <auto-generated />
namespace WebApplication3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Rol1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rol1));
        
        string IMigrationMetadata.Id
        {
            get { return "202001271225069_Rol1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
